version: '3.9'

services:

  ratestask_db:
    image: ratestask_db
    build:
      context: ratestask
    container_name: ratestask_db
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ratestask_data:/var/lib/postgresql/data


  ratestask_api:
    image: ratestask_api
    build:
      context: .
    container_name: ratestask_api
    depends_on:
      - ratestask_db
    env_file:
      - .env
    ports:
      - 8000:8000

volumes:
  ratestask_data:

